on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 19.x] # add node versions here
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm i -g yarn
          yarn install

      - name: Build
        run: yarn build # run build


    #   - name: Test
    #     run: yarn test  # run tests
